-d D:\Gowin_Folder\Projects\freq_meter_calc_2\impl\gwsynthesis\freq_meter_calc_2.vg
-p GW5A-25A-UBGA324-2
-pn GW5A-LV25UG324C2/I1
-cst D:\Gowin_Folder\Projects\freq_meter_calc_2\src\freq_meter_calc_2.cst
-cfg D:\Gowin_Folder\Projects\freq_meter_calc_2\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
-enable_dsrm 0
